name: Build and Deploy Storybook
on:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: storybook-test_group # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "docs-build"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: ğŸ”§ Install dependencies
        run: npm i
      - name: ğŸ— Build
        run: npm run build-storybook
      - name: ğŸ“ Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs-build"
      - name: "ğŸš€ Deploy to Azure WebApp"
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_STONE_086AAE41E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          app_location: "docs-build"
          skip_app_build: true
          skip_api_build: true
